blueprint:
  name: Zalo Bot - Send Image by Camera Name
  author: your_name
  description: >-
    # Script to send camera snapshot via Zalo Bot

    ## Blueprint Setup

    ### Required

    * Thêm từng camera một với tên và URL, có thể thêm nhiều camera bằng nút '+' trong giao diện.
    * Khi chat với bot, nhập đúng tên camera để nhận ảnh tương ứng.
    * Cần cấu hình đúng thread_id và account_selection của Zalo Bot.

    ### Optional

    * Có thể thêm nội dung message kèm theo ảnh.
    * Có thể cấu hình TTL để tự thu hồi tin nhắn.

    ### Note

    * Nếu nhập tên camera không đúng, bot sẽ báo lỗi.
    * Script này không tự động gửi ảnh, chỉ gửi khi có yêu cầu đúng tên camera.
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    cameras:
      name: Camera List
      description: Danh sách các camera (thêm từng camera một).
      selector:
        list:
          item:
            type: object
            properties:
              name:
                name: Tên camera
                selector:
                  text:
              url:
                name: URL ảnh
                selector:
                  text:
    camera_name:
      name: Camera Name
      description: |
        Tên camera cần gửi (ví dụ: san, cong, kho...)
      selector:
        text:
    thread_id:
      name: Zalo Thread ID
      description: Thread ID để gửi tin nhắn.
      selector:
        text:
    account_selection:
      name: Zalo Bot Account
      description: Số điện thoại hoặc định danh tài khoản Zalo Bot.
      selector:
        text:
    message:
      name: Message (Optional)
      description: Nội dung kèm theo ảnh (tùy chọn).
      selector:
        text:
      default: ""
    ttl:
      name: TTL (Optional)
      description: Thời gian tự thu hồi tin nhắn (ms), mặc định 20000.
      selector:
        number:
          min: 0
          step: 1
      default: 20000
sequence:
  - variables:
      cameras: "{{ cameras }}"
      camera_name: "{{ camera_name }}"
      image_url: >
        {% set url = None %}
        {% for cam in cameras %}
          {% if cam.name == camera_name %}
            {% set url = cam.url %}
          {% endif %}
        {% endfor %}
        {{ url }}
      thread_id: "{{ thread_id }}"
      account_selection: "{{ account_selection }}"
      message: "{{ message }}"
      ttl: "{{ ttl }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ image_url is not none and image_url != '' }}"
        sequence:
          - service: zalo_bot.send_image
            data:
              type: "1"
              ttl: "{{ ttl }}"
              image_path: "{{ image_url }}"
              thread_id: "{{ thread_id }}"
              account_selection: "{{ account_selection }}"
              message: >
                {% if message %}
                  {{ message }} (Camera: {{ camera_name }})
                {% else %}
                  Camera: {{ camera_name }}
                {% endif %}
      - default:
          - service: zalo_bot.send_message
            data:
              thread_id: "{{ thread_id }}"
              account_selection: "{{ account_selection }}"
              message: "Không tìm thấy camera '{{ camera_name }}' trong danh sách."
mode: single
