blueprint:
  name: Zalo Bot - Send Image by Camera Name
  author: your_name
  description: >
    Gửi ảnh từ nhiều camera qua Zalo Bot bằng service zalo_bot.send_image. Chỉ cần nhập tên camera, bot sẽ gửi đúng ảnh.
  domain: script
  homeassistant:
    min_version: 2025.8.0
  input:
    cameras:
      name: Camera List
      description: Danh sách camera (dạng JSON: {"san": "http://...", "cong": "http://..."}).
      selector:
        text:
          multiline: true
    camera_name:
      name: Camera Name
      description: Tên camera cần gửi (ví dụ: san, cong, kho...).
      selector:
        text:
    thread_id:
      name: Zalo Thread ID
      description: Thread ID để gửi tin nhắn.
      selector:
        text:
    account_selection:
      name: Zalo Bot Account
      description: Số điện thoại hoặc định danh tài khoản Zalo Bot.
      selector:
        text:
    message:
      name: Message (Optional)
      description: Nội dung kèm theo ảnh (tùy chọn).
      selector:
        text:
      default: ""
    ttl:
      name: TTL (Optional)
      description: Thời gian tự thu hồi tin nhắn (ms), mặc định 20000.
      selector:
        number:
          min: 0
          step: 1
      default: 20000
sequence:
  - variables:
      cameras: "{{ namespace('json').loads(!input.cameras) }}"
      camera_name: !input.camera_name
      image_url: "{{ cameras.get(camera_name) }}"
      thread_id: !input.thread_id
      account_selection: !input.account_selection
      message: !input.message
      ttl: !input.ttl
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ image_url is not none }}"
        sequence:
          - service: zalo_bot.send_image
            data:
              type: "1"
              ttl: "{{ ttl }}"
              image_path: "{{ image_url }}"
              thread_id: "{{ thread_id }}"
              account_selection: "{{ account_selection }}"
              message: >
                {% if message %}
                  {{ message }} (Camera: {{ camera_name }})
                {% else %}
                  Camera: {{ camera_name }}
                {% endif %}
      - default:
          - service: zalo_bot.send_message
            data:
              thread_id: "{{ thread_id }}"
              account_selection: "{{ account_selection }}"
              message: "Không tìm thấy camera '{{ camera_name }}' trong danh sách."
mode: single
